### ISSUE TITLE
Looping through the skills

### ISSUE THREAD

**Issue by peterharmouch** [artberryx/LSD#5]
Hello, I have 2 questions. One regarding the algorithm itself and the other regarding an implementation detail of your code:

In the algorithm described in appendix C of the paper, is this a training procedure that is repeated for each skill? In other words, can we rewrite the pseudocode as follows:

```
for skill in range(# skills):
    initialize_skill_policy_and_representation()
    while not converged:
        for i in range(# episodes per epoch):
            z = sample_skill from distribution()
            trajectory = sample_trajectory_with_policy()
        reward = compute_reward()
        representation_function = update_te_with_sgd()
        policy = update_op_with_sac()
        converged = check_convergence()
```

If this is a correct understanding of the algorithm, could you please specify where in your code we can find the line that corresponds to: "for skill in range(# skills):"?

If this is not how the algorithm works, then what defines the number of skills learned and how is it integrated in the algorithm ?

Thank you in advance for your response.

**Comment by seohongpark** [comment]
Hi, thank you for the question.

No, we do not have a per-skill loop (i.e., there is no such an outer loop).
At every epoch, we sample 20 trajectories, where for each trajectory, we first sample a skill `z` from the prior distribution `p(z)` (which is either a normal or uniform distribution) and then sample a trajectory with the current skill policy `\pi(a|s, z)`.
The number of skills is defined by the `--dim_option` and `--discrete` flags. For example, the agent learns 8 skills if we set `--discrete=1 --dim_option=8`. The 8 skills are learned simultaneously so that they can be maximally different from one another.
